### ISSUE TITLE
Item dupe

### ISSUE THREAD

**Issue by mvolotov** [MineVid/dtlTraders-plus-#12] opened 2021-09-18 08:46 UTC
Good afternoon!

I found a bug on my server. If you hover the cursor over an item in the store, and then click a combination like 3+e, where 3 is a slot from the hotbar, and e is the closure of the inventory, then the item gets into the selected hotbar cell for free and the store closes.

PaperMC: 1.16.5#768
dtlTraders-plus: 6.4.1

**Comment by notbike** [comment] 2022-02-15 00:26
confirmed, dupe worked on 1.18.1, purpur, plugin ver. 6.4.7

**Comment by MinevidOld** [comment] 2022-02-15 09:31
The number thing is fixed in my test version. Will post a update as soon as possible. (Currently at work)

**Comment by MinevidOld** [comment] 2022-02-15 20:02
Fixed in latest version (6.4.9)

**Closed as completed by MinevidOld** 2022-02-15 20:02 UTC
Labels: Bug, Fixed
