### ISSUE TITLE
Visual Duplication / Steal items via F / Offhand

### ISSUE THREAD

**Issue by smoke-kush** [MineVid/dtlTraders-plus-#11] opened 2021-06-10 20:05 UTC
So we discovered that we can take items by using f / offhand button then using f/offhand to move to inventory or armour slot. These apply none of the perks the item should and if you click the item it dissapears but it would be nice to see this fixed. 

Here is some photos for reference. 

If you need a better explanation my discord is Smoke_Kush#1439.

Thanks. 
![2021-06-10_20 58 00](https://user-images.githubusercontent.com/85659601/121589933-952d9c00-ca2f-11eb-85e4-6a26da7ab4ca.png)
![2021-06-10_20 58 12](https://user-images.githubusercontent.com/85659601/121589936-95c63280-ca2f-11eb-9245-b14e4a382e7c.png)
![2021-06-10_20 59 22](https://user-images.githubusercontent.com/85659601/121589937-965ec900-ca2f-11eb-8fce-a972c7f4772a.png)

**Comment by notbike** [comment] 2022-02-15 00:28
omg, confirmed,
1.18.1
purpur
6.4.7.

wow, did not know there are this many dupe methods in the plugin.

**Comment by MinevidOld** [comment] 2022-02-15 09:15
> 

There is no need to be like "wow, did not know there are this many dupe methods in the plugin.".

**Comment by MinevidOld** [comment] 2022-02-15 10:05
This bug can't be fixed with Spigot as this is a known Client-Side bug. 


Reference: 
https://hub.spigotmc.org/jira/browse/SPIGOT-6291
https://hub.spigotmc.org/jira/browse/PLUG-409

**Closed as completed by MinevidOld** 2022-02-15 10:05 UTC
Labels: Bug
